export const OrderStatus = Object.freeze({
  AWAITING_DEPOSIT: "AWAITING_DEPOSIT",
  DEPOSIT_CONFIRMED: "DEPOSIT_CONFIRMED",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELED: "CANCELED",
});
